[package]
name = "hello"
version = "0.1.0"
authors = ["Jeff Foster <jeff.foster@acm.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
