[package]
name = "mandlebrot"
version = "0.1.0"
authors = ["Jeff Foster <jeff.foster@acmo.rg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
image = "0.13.0"
crossbeam = "0.8"