[package]
name = "orbit"
version = "0.1.0"
authors = ["Jeff Foster <jeff.foster@red-gate.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-colorizer = "1"
rand = "0.7.3"
image = "0.23.14"